services:
  trino:
    image: trinodb/trino:447
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dw
      POSTGRES_DB: shipments
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dw -d shipments"]
      interval: 10s
      timeout: 5s
      retries: 15

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ops
      MYSQL_USER: dw
      MYSQL_PASSWORD: dw
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpw --silent"]
      interval: 10s
      timeout: 5s
      retries: 15

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    depends_on:
      - trino 
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_OIDC_ENABLED: "true"
      MB_OIDC_ISSUER: "http://keycloak:8080/realms/datawave"
      MB_OIDC_CLIENT_ID: "metabase"
      MB_OIDC_CLIENT_SECRET: "t03vw2QkUtm4N6XLO4vJjHlxG1vznPVQ"
      MB_OIDC_SCOPE: "openid email profile"
    volumes:
      - metabase-data:/metabase-data
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_URL: "http://localhost:8081"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8081:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    restart: unless-stopped
    depends_on:
      - keycloak
      - trino
    ports:
      - "8082:4180"
    command:
    - --http-address=0.0.0.0:4180
    - --provider=oidc
    - --skip-oidc-discovery=true
    - --oidc-issuer-url=http://localhost:8081/realms/datawave
    - --login-url=http://localhost:8081/realms/datawave/protocol/openid-connect/auth
    - --redeem-url=http://keycloak:8080/realms/datawave/protocol/openid-connect/token
    - --validate-url=http://keycloak:8080/realms/datawave/protocol/openid-connect/userinfo
    - --oidc-jwks-url=http://keycloak:8080/realms/datawave/protocol/openid-connect/certs
    - --client-id=trino-proxy
    - --client-secret=V0SpdehluCifELchnUB5wC4eIm2SJXnU
    - --cookie-secret=1k0KmnaiQH9kdNEasGq7HA==
    - --email-domain=*
    - --upstream=http://trino:8080/
    - --redirect-url=http://localhost:8082/oauth2/callback
    - --cookie-secure=false
    - --skip-provider-button=true
volumes:
  metabase-data:
  keycloak-data: