services:
  trino:
    image: trinodb/trino:447
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dw
      POSTGRES_DB: shipments
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dw -d shipments"]
      interval: 10s
      timeout: 5s
      retries: 15

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ops
      MYSQL_USER: dw
      MYSQL_PASSWORD: dw
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpw --silent"]
      interval: 10s
      timeout: 5s
      retries: 15

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    depends_on:
      - trino 
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data: